---
title: "Leveraging remote sensing for Public Health"
subtitle: "Visiting the Geospatial Analytics Center at NCSU"
date: '`r Sys.Date()`'
author: "Verónica Andreo"
toc: true
---

## Overview

Vector-borne and zoonotic diseases are responsible for one-sixth of disease 
and disability worldwide. Their distribution and spread is highly dependent 
on the environment. In the face of the environmental changes brought about 
by the Earth system crisis, remote sensing has gained renewed relevance for
public health applications. For example, time series of remotely sensed 
variables can be used to understand the spatio-temporal conditions that 
favor mosquito populations and may pose a high risk of West Nile Fever 
outbreaks. In this talk I'll show how we use remote sensing data of different
spatial and temporal resolutions to predict the risk of diseases such as 
hantavirus, dengue and leishmaniasis, to allocate sensors for mosquito 
sampling, and to quantify access to health care, among others. I will also 
discuss various limitations, challenges, and future directions in the use of
remote sensing for operational early warning systems and applications to 
support timely decision making in the field of Public Health. 
Spoiler alert! GRASS GIS is one of the main characters in this journey.

## Contents

1.  Lecture: "**Environmental drivers of vector-borne and zoonotic diseases: Leveraging remote sensing for Public Health**"
    1. Motivation
    2. Health Geography
    3. Disease Ecology
    4. Leveraging remote sensing for Disease Ecology
       - Resolution vs scale
       - How can we use RS?
       - Examples
    5. Gaps, challenges and opportunities
    6. Conclusion
2.  Studio: "**Using satellite data for species distribution modeling with GRASS GIS and R**"
    1. Intro to GRASS GIS
    2. Processing data in GRASS
    3. Modeling species distributions with R


