---
title: "Using Satellite Data for Species Distribution Modeling with GRASS GIS and R"
author: "Verónica Andreo"
date: '`r Sys.Date()`'
---

Traditionally, species distribution models (SDM) use climatic data as predictors of habitat suitability for the target species. In this studio, we will explore the use of satellite data to derive relevant predictors. The satellite data processing, from download to analysis, will be performed using GRASS GIS software functionality. Then, we'll read our predictors within R and perform SDM, visualize and analyze results there, to then exemplify how to write the output distribution maps back into GRASS.

# Getting ready

We'll run this session online within the [Whole Tale platform](https://wholetale.org/). 
Whole Tale is an NSF-funded Data Infrastructure Building Block (DIBBS) initiative
to build a scalable, open source, web-based, multi-user platform for reproducible
research. It enables the creation, publication, and execution of tales - executable
research objects that capture data, code, and the complete software environment 
used to produce research findings. It's also great for teaching, as participants
do not need to install all software packages required. They only need to register 
with institutional or personal email and they are ready to go!

**Run the session online:** [Using satellite data for SDM with GRASS GIS and R](https://dashboard.wholetale.org/run/64388157b3b74e434bd8f1ac?tab=metadata)


## Software 

If you still want to run the workshop locally, you'll find instructions and 
requirements below.

### GRASS GIS

We will use **GRASS GIS 8.2+**. It can be installed either 
through standalone installers/binaries or through
[OSGeo-Live](https://live.osgeo.org/en/index.html) 
(a linux based virtual machine which includes all OSGeo software and packages).

##### MS Windows

There are two different options to install GRASS GIS in MS Windows:

1. [Standalone installer 64-bit](https://grass.osgeo.org/grass82/binary/mswindows/native/WinGRASS-8.2.1-1-Setup.exe) 
2. [OSGeo4W 64-bit](http://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe) 

For Windows users, **we strongly recommend installing GRASS GIS through the OSGeo4W package** (second option), 
since it allows to install all OSGeo software and resolves dependencies. 

##### Ubuntu Linux

Install GRASS GIS 8.2+ from the "unstable" package repository:

```bash
  sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  sudo apt-get update
  sudo apt-get install grass grass-gui grass-dev
```

##### Fedora, openSuSe Linux

For other Linux distributions including **Fedora** and **openSuSe**, simply 
install GRASS GIS with the respective package manager. See also [here](https://grass.osgeo.org/download/linux/)

##### Mac OS

Find GRASS GIS binaries on <http://grassmac.wikidot.com/> or install the 
latest available version from [MacPorts](https://ports.macports.org/port/grass/).

#### GRASS GIS Add-ons 

* [r.bioclim](https://grass.osgeo.org/grass-stable/manuals/addons/r.bioclim.html): Calculates bioclimatic indices as those in [WorldClim](https://www.worldclim.org/bioclim).

Install with `g.extension extension=name_of_addon`

### R packages

The following R packages should be installed beforehand:

```r
  install.packages(c("rgrass","terra","raster","sf","mapview","biomod2","dismo","usdm","SDMtune","zeallot","rJava","ggpubr"))
```

### Python libraries

The following Python libraries should be installed beforehand:

```bash
  pip install folium 
```

## Other software

We will use the software **MaxEnt** to model habitat suitability. It can be 
downloaded from: <https://biodiversityinformatics.amnh.org/open_source/maxent/>

## Data

Download the following ready to use *location* with reconstructed daily LST 
averages (@metz_new_2017) for Northern Italy. This dataset is courtesy of
[mundialis GmbH & Co. KG](mundialis.de/en/).

* [Northern Italy (1.7 Gb)](https://drive.google.com/file/d/1z1b2NLC4Z6yzz_57RddTdRRK_gUkd7fU/view?usp=sharing)

We will also use a points vector map representing *Aedes albopictus* presence data:

* [Mosquito occurrence data](data/aedes_albopictus.gpkg)


## References

:::{#refs}
:::

<!-- - https://github.com/veroandreo/foss4g2022_grass4rs -->
<!-- - https://github.com/veroandreo/grass_opengeohub2021 -->
<!-- - Neteler, M. and Mitasova, H. (2008): *Open Source GIS: A GRASS GIS Approach*. Third edition. ed. Springer, New York. [Book site](https://grassbook.org/) -->
<!-- - Neteler, M., Bowman, M.H., Landa, M. and Metz, M. (2012): *GRASS GIS: a multi-purpose Open Source GIS*. Environmental Modelling & Software, 31: 124-130 [DOI](http://dx.doi.org/10.1016/j.envsoft.2011.11.014) -->
<!-- - Gebbert, S. and Pebesma, E. (2014). *A temporal GIS for field based environmental modeling*. Environmental Modelling & Software, 53, 1-12. [DOI](https://doi.org/10.1016/j.envsoft.2013.11.001) -->
<!-- - Gebbert, S. and Pebesma, E. (2017). *The GRASS GIS temporal framework*. International Journal of Geographical Information Science, 31, 1273-1292. [DOI](http://dx.doi.org/10.1080/13658816.2017.1306862) -->
<!-- - Gebbert, S., Leppelt, T. and Pebesma, E. (2019). *A Topology Based Spatio-Temporal Map Algebra for Big Data Analysis*. Data, 4, 86. [DOI](https://doi.org/10.3390/data4020086) -->